# Generated by Django 2.1.7 on 2019-03-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190304_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametro',
            new_name='Parametros',
        ),
    ]
