# Generated by Django 2.1.7 on 2019-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
