# Generated by Django 2.1.7 on 2019-03-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='veiculo',
            new_name='mensalista',
        ),
    ]
