# Generated by Django 2.1.7 on 2019-03-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190305_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parametros'),
        ),
    ]
