# Generated by Django 2.1.7 on 2019-03-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190305_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
